"""
Database models for the application.

Defines the User model and helper methods for password hashing
and authentication integration with Flask-Login.
"""

from . import db
from flask_login import UserMixin
from .constants import username_max_length
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    """
    User database model.

    Inherits UserMixin to work with Flask-Login.
    """
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(username_max_length), unique=True, nullable=False)
    # Store the full password hash generated by Werkzeug
    password_hash = db.Column(db.String(225), nullable=False)
    
    def set_password(self, password):
        """
        Hash and store the user's password.

        Uses Werkzeug's generate_password_hash(), which defaults
        to a salted PBKDF2-SHA256 key derivation function.
        """
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """
        Verify a plaintext password against the stored hash.
        """
        return check_password_hash(self.password_hash, password)

